---
title: "Untitled"
author: "Manuel Haqiqatkhah"
date: "March 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Multi-dimensional IRT and Multi-dimensional Constructs for Emotions {#mirt}


Here I present what I've done with `mirt`.

```{r, include=TRUE}
#, code = readLines("../Codes/sampled-model-comp.R")}
library(mirt)
library(plyr)
library(dplyr)

sampled.path <- "../Processed data/sampled mirt models"
sampled.names <- list.files(path = sampled.path, pattern = "*.RData")


list.of.names <- list('CLINICAL ESM','Cogito','ELISE ESM14', 'JULIAN EGON',
                      'KATHLEEN STRESSKLINIEK', 'Laura ESM 2014','Laura ESM 2016',
                      'LONGITUDINAL W1', 'LONGITUDINAL W2', 'LONGITUDINAL W3','MARLIES BPD',
                      'MDD BPD TRULL', 'MDD GOTLIB', 'MTURK DAILY DIARY', 
                      'PETEMADDY')


outcomes <- data.frame(matrix(ncol = 15, nrow = 1))
colnames(outcomes) <- list.of.names

criterion <- "HQ"
for(sampled in sampled.names){
  load(paste0("../Processed data/sampled mirt models/", sampled, sep = ""))
  name <- sampled.mirt$name
  round <- sampled.mirt$round
  outcomes[round, name] <- sampled.mirt %>% my.mirt.comparison(criterion = criterion)
  sampled.mirt$model %>% l_ply(summary)
}

```

